os: linux
dist: xenial
language: ruby
rvm:
  - 2.6.5
gemfile:
  - gemfiles/Gemfile-rails.5.2.x
  - gemfiles/Gemfile-rails.6.0.x
  - gemfiles/Gemfile-rails-edge
before_install: 
  - sudo gem install bundler