os: linux
dist: xenial
language: ruby
before_install: 
  - sudo rvm install 2.6.5
  - sudo rvm use 2.6.5
  - yes | gem update --system --force
  - sudo gem install bundler
install:
  - sudo gem install rails
