dist: xenial
os: linux
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install: 
  - yes | gem update --system --force
  - gem --version
  - bundle update --bundler
  - git clone https://github.com/TravisToolbox/rubocop-travis.git
  - git clone https://github.com/rubocop-hq/rubocop.git
install:
  - ./rubocop-travis/install.sh
  - gem install rubocop
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - ./rubocop-travis/scan.sh
  - gem 'rubocop'