os: linux
language: ruby
rvm:
  - 2.6.5
before_install: 
  - yes | gem update --system --force
  - gem --version
  - bundle update --bundler
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate